<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>KoreEngine</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
  </ItemGroup>

  <ItemGroup>
    <!-- SDL3-CS etc. arrivent transitivement via cette référence — pas besoin
         de les redéclarer ici. -->
    <ProjectReference Include="..\KoreEngine.Runtime\KoreEngine.Runtime.csproj" />
  </ItemGroup>

</Project>
