using SDL3;

namespace KoreEngine
{
    public enum KeyCode {
        A = (int)SDL.Keycode.A,
        B = (int)SDL.Keycode.B,
        C = (int)SDL.Keycode.C,
        D = (int)SDL.Keycode.D,
        E = (int)SDL.Keycode.E,
        F = (int)SDL.Keycode.F,
        G = (int)SDL.Keycode.G,
        H = (int)SDL.Keycode.H,
        I = (int)SDL.Keycode.I,
        J = (int)SDL.Keycode.J,
        K = (int)SDL.Keycode.K,
        L = (int)SDL.Keycode.L,
        M = (int)SDL.Keycode.M,
        N = (int)SDL.Keycode.N,
        O = (int)SDL.Keycode.O,
        P = (int)SDL.Keycode.P,
        Q = (int)SDL.Keycode.Q,
        R = (int)SDL.Keycode.R,
        S = (int)SDL.Keycode.S,
        T = (int)SDL.Keycode.T,
        U = (int)SDL.Keycode.U,
        V = (int)SDL.Keycode.V,
        W = (int)SDL.Keycode.W,
        X = (int)SDL.Keycode.X,
        Y = (int)SDL.Keycode.Y,
        Z = (int)SDL.Keycode.Z,

        Alpha0 = (int)SDL.Keycode.Alpha0,
        Alpha1 = (int)SDL.Keycode.Alpha1,
        Alpha2 = (int)SDL.Keycode.Alpha2,
        Alpha3 = (int)SDL.Keycode.Alpha3,
        Alpha4 = (int)SDL.Keycode.Alpha4,
        Alpha5 = (int)SDL.Keycode.Alpha5,
        Alpha6 = (int)SDL.Keycode.Alpha6,
        Alpha7 = (int)SDL.Keycode.Alpha7,
        Alpha8 = (int)SDL.Keycode.Alpha8,
        Alpha9 = (int)SDL.Keycode.Alpha9,

        Keypad0 = (int)SDL.Keycode.Kp0,
        Keypad1 = (int)SDL.Keycode.Kp1,
        Keypad2 = (int)SDL.Keycode.Kp2,
        Keypad3 = (int)SDL.Keycode.Kp3,
        Keypad4 = (int)SDL.Keycode.Kp4,
        Keypad5 = (int)SDL.Keycode.Kp5,
        Keypad6 = (int)SDL.Keycode.Kp6,
        Keypad7 = (int)SDL.Keycode.Kp7,
        Keypad8 = (int)SDL.Keycode.Kp8,
        Keypad9 = (int)SDL.Keycode.Kp9,

        F1 = (int)SDL.Keycode.F1,
        F2 = (int)SDL.Keycode.F2,
        F3 = (int)SDL.Keycode.F3,
        F4 = (int)SDL.Keycode.F4,
        F5 = (int)SDL.Keycode.F5,
        F6 = (int)SDL.Keycode.F6,
        F7 = (int)SDL.Keycode.F7,
        F8 = (int)SDL.Keycode.F8,
        F9 = (int)SDL.Keycode.F9,
        F10 = (int)SDL.Keycode.F10,
        F11 = (int)SDL.Keycode.F11,
        F12 = (int)SDL.Keycode.F12,
        F13 = (int)SDL.Keycode.F13,
        F14 = (int)SDL.Keycode.F14,
        F15 = (int)SDL.Keycode.F15,
        F16 = (int)SDL.Keycode.F16,
        F17 = (int)SDL.Keycode.F17,
        F18 = (int)SDL.Keycode.F18,
        F19 = (int)SDL.Keycode.F19,
        F20 = (int)SDL.Keycode.F20,
        F21 = (int)SDL.Keycode.F21,
        F22 = (int)SDL.Keycode.F22,
        F23 = (int)SDL.Keycode.F23,
        F24 = (int)SDL.Keycode.F24,
    }
}
